services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: db_user
      POSTGRES_DB: ms_talker_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data:
